<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="$(HostRepositoryRoot)/Host/MyAvaloniaManagement/MyAvaloniaManagement.csproj"/><ProjectReference Include="../../src/VideoSecurityPlayer.Plugin/VideoSecurityPlayer.Plugin.csproj"/><PackageReference Include="Microsoft.Extensions.DependencyInjection"/><PackageReference Include="Microsoft.NET.Test.Sdk"/><PackageReference Include="xunit"/><PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all"/></ItemGroup><Target Name="RequireHostRepository" BeforeTargets="PrepareForBuild"><Error Condition="'$(HostRepositoryRoot)' == ''" Text="Specify -p:HostRepositoryRoot=host source repository."/></Target><ItemGroup><PackageReference Include="coverlet.collector" PrivateAssets="all" /></ItemGroup></Project>